Repository DevNatan/inventory-framework, pull requests merged in 2022-04, with the labels that each got.

#46 Set JB annotations dependency scope to `compileOnlyApi`
  CHANGELOG.md
  build.gradle
Labels: build-system, thirdparty

#44 Previous and next page items aren't displayed if item slot is manually defined
  CHANGELOG.md
  src/main/java/me/saiintbrisson/minecraft/PaginatedView.java
Labels: bug

#47 Catch exception on paginated rendering
  CHANGELOG.md
  src/main/java/me/saiintbrisson/minecraft/PaginatedView.java
Labels: bug

#66 View options documentation on readme
  README.md
Labels: documentation

#60 View initial global `onRender` error handling
  src/main/java/me/saiintbrisson/minecraft/View.java
Labels: bug

#59 View `onOpen` error handling
  src/main/java/me/saiintbrisson/minecraft/View.java
Labels: bug

#56 Allow getting current title from context inventory
  src/main/java/me/saiintbrisson/minecraft/ViewContext.java
Labels: api-design

#62 Possibility to get the data source of a page
  src/main/java/me/saiintbrisson/minecraft/PaginatedViewContext.java
Labels: api-design

#75 replaced 'BLAZE_ROW' to 'BLAZE_ROD'.
  README.md
Labels: documentation

#65 Transitive context data
  README.md
  src/main/java/me/saiintbrisson/minecraft/ViewContext.java
Labels: feature

#70 User-defined layout pattern
  src/main/java/me/saiintbrisson/minecraft/DelegatedViewContext.java
  src/main/java/me/saiintbrisson/minecraft/LayoutPattern.java
  src/main/java/me/saiintbrisson/minecraft/PaginatedView.java
  src/main/java/me/saiintbrisson/minecraft/PaginatedViewContext.java
  src/main/java/me/saiintbrisson/minecraft/View.java
  src/main/java/me/saiintbrisson/minecraft/ViewContext.java
  src/main/java/me/saiintbrisson/minecraft/VirtualView.java
Labels: feature

#55 Custom "on click outside" inventory handler
  src/main/java/me/saiintbrisson/minecraft/View.java
  src/main/java/me/saiintbrisson/minecraft/ViewListener.java
Labels: feature

#81 Pagination item overrides already set item on re render
  src/main/java/me/saiintbrisson/minecraft/PaginatedView.java
  src/main/java/me/saiintbrisson/minecraft/PaginatedViewContext.java
  src/main/java/me/saiintbrisson/minecraft/View.java
  src/main/java/me/saiintbrisson/minecraft/ViewItem.java
Labels: bug

#82 Remove `implements Closeable` from View
  src/main/java/me/saiintbrisson/minecraft/View.java
Labels: api-design

#84 Add `api-version` to plugin.yml
  src/main/resources/plugin.yml
Labels: compatibility
