Repository DevNatan/inventory-framework, pull requests merged in 2023-05, with the labels that each got.

#356 Run workflows on PRs
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/generate-artifacts.yml
Labels: ci

#357 Run workflows on PRs
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/generate-artifacts.yml
Labels: ci

#353 feat: infer inv size from layout
  platform/src/main/java/me/devnatan/inventoryframework/pipeline/OpenInterceptor.java
  platform/src/test/java/me/devnatan/inventoryframework/pipeline/OpenInterceptorTest.java
Labels: feature

#358 Kyori Adventure library support
  .github/workflows/build.yml
  .github/workflows/generate-artifacts.yml
  .github/workflows/publish.yml
  api/build.gradle
  api/src/main/java/me/devnatan/inventoryframework/ViewConfig.java
  api/src/main/java/me/devnatan/inventoryframework/ViewConfigBuilder.java
  api/src/main/java/me/devnatan/inventoryframework/internal/ElementFactory.java
  build.gradle
  bukkit/build.gradle
  bukkit/src/main/java/me/devnatan/inventoryframework/internal/BukkitElementFactory.java
  bukkit/src/main/java/me/devnatan/inventoryframework/internal/InventoryFactory.java
  bukkit/src/main/java/me/devnatan/inventoryframework/internal/PaperInventoryFactory.java
  bukkit/src/main/java/me/devnatan/inventoryframework/runtime/InventoryFramework.java
  bukkit/src/main/java/me/devnatan/inventoryframework/runtime/thirdparty/InventoryUpdate.java
  gradle/libs.versions.toml
  platform/src/main/java/me/devnatan/inventoryframework/pipeline/OpenInterceptor.java
  platform/src/test/java/me/devnatan/inventoryframework/pipeline/OpenInterceptorTest.java
  test/src/main/java/me/devnatan/inventoryframework/internal/MockElementFactory.java
Labels: feature, platform-bukkit, third-party

#361 Inter-view openings and RootView documentation improvements
  api/src/main/java/me/devnatan/inventoryframework/RootView.java
  api/src/main/java/me/devnatan/inventoryframework/Viewer.java
  api/src/main/java/me/devnatan/inventoryframework/context/IFConfinedContext.java
  api/src/main/java/me/devnatan/inventoryframework/context/IFContext.java
  api/src/main/java/me/devnatan/inventoryframework/internal/ElementFactory.java
  bukkit/src/main/java/me/devnatan/inventoryframework/ViewFrame.java
  bukkit/src/main/java/me/devnatan/inventoryframework/context/CloseContext.java
  bukkit/src/main/java/me/devnatan/inventoryframework/context/OpenContext.java
  bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotContext.java
  bukkit/src/main/java/me/devnatan/inventoryframework/internal/BukkitElementFactory.java
  bukkit/src/main/java/me/devnatan/inventoryframework/pipeline/ItemCloseOnClickInterceptor.java
  bukkit/src/main/java/me/devnatan/inventoryframework/runtime/listener/IFInventoryListener.java
  bukkit/src/test/java/me/devnatan/inventoryframework/runtime/listener/IFInventoryListenerTest.java
  framework/src/main/java/me/devnatan/inventoryframework/DefaultRootView.java
  framework/src/main/java/me/devnatan/inventoryframework/context/BaseViewContext.java
  platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java
  platform/src/main/java/me/devnatan/inventoryframework/context/ConfinedContext.java
  test/src/main/java/me/devnatan/inventoryframework/internal/MockElementFactory.java
Labels: bug, documentation

#363 Missing Bukkit cancelOnDrag implementation
  api/src/main/java/me/devnatan/inventoryframework/ViewConfig.java
  api/src/main/java/me/devnatan/inventoryframework/ViewConfigBuilder.java
  bukkit/src/main/java/me/devnatan/inventoryframework/pipeline/GlobalClickInterceptor.java
  bukkit/src/main/java/me/devnatan/inventoryframework/runtime/listener/IFInventoryListener.java
Labels: bug, platform-bukkit

#366 Try to fix source and target compatibility issues
  bukkit/build.gradle
  bukkit/src/main/java/me/devnatan/inventoryframework/runtime/InventoryFramework.java
  bukkit/src/main/java/me/devnatan/inventoryframework/runtime/thirdparty/Metrics.java
  jitpack.yml
  library.gradle
Labels: build-system

#374 Publish on Maven Central
  .github/workflows/publish.yml
  bom/build.gradle
  build.gradle
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  jitpack.yml
  publish.gradle
Labels: ci

#354 Inventory updates
  api/src/main/java/me/devnatan/inventoryframework/RootView.java
  api/src/main/java/me/devnatan/inventoryframework/ViewConfig.java
  api/src/main/java/me/devnatan/inventoryframework/ViewConfigBuilder.java
  api/src/main/java/me/devnatan/inventoryframework/context/IFConfinedContext.java
  api/src/main/java/me/devnatan/inventoryframework/context/IFContext.java
  api/src/main/java/me/devnatan/inventoryframework/context/IFRenderContext.java
  api/src/main/java/me/devnatan/inventoryframework/internal/ElementFactory.java
  bukkit/src/main/java/me/devnatan/inventoryframework/View.java
  bukkit/src/main/java/me/devnatan/inventoryframework/ViewFrame.java
  bukkit/src/main/java/me/devnatan/inventoryframework/context/CloseContext.java
  bukkit/src/main/java/me/devnatan/inventoryframework/context/OpenContext.java
  bukkit/src/main/java/me/devnatan/inventoryframework/context/RenderContext.java
  bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotContext.java
  bukkit/src/main/java/me/devnatan/inventoryframework/internal/BukkitElementFactory.java
  bukkit/src/main/java/me/devnatan/inventoryframework/internal/BukkitTaskJobImpl.java
  bukkit/src/main/java/me/devnatan/inventoryframework/internal/InventoryFactory.java
  bukkit/src/main/java/me/devnatan/inventoryframework/runtime/util/InventoryUtils.java
  framework/src/main/java/me/devnatan/inventoryframework/DefaultRootView.java
  framework/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
  framework/src/main/java/me/devnatan/inventoryframework/context/BaseViewContext.java
  framework/src/main/java/me/devnatan/inventoryframework/pipeline/FirstRenderInterceptor.java
  framework/src/main/java/me/devnatan/inventoryframework/pipeline/ScheduledUpdateAfterCloseInterceptor.java
  framework/src/main/java/me/devnatan/inventoryframework/pipeline/ScheduledUpdateAfterRenderInterceptor.java
  framework/src/main/java/me/devnatan/inventoryframework/state/BaseMutableState.java
  framework/src/main/java/me/devnatan/inventoryframework/state/BaseState.java
  framework/src/main/java/me/devnatan/inventoryframework/state/MutableGenericStateImpl.java
  framework/src/main/java/me/devnatan/inventoryframework/state/MutableIntStateImpl.java
  platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java
  platform/src/main/java/me/devnatan/inventoryframework/context/ConfinedContext.java
  platform/src/main/java/me/devnatan/inventoryframework/context/PlatformRenderContext.java
  platform/src/main/java/me/devnatan/inventoryframework/pipeline/PlatformCloseInterceptor.java
  platform/src/main/java/me/devnatan/inventoryframework/pipeline/PlatformInitInterceptor.java
  platform/src/main/java/me/devnatan/inventoryframework/pipeline/PlatformOpenInterceptor.java
  platform/src/main/java/me/devnatan/inventoryframework/pipeline/PlatformUpdateHandlerInterceptor.java
  platform/src/test/java/me/devnatan/inventoryframework/context/PlatformRenderContextTest.java
  platform/src/test/java/me/devnatan/inventoryframework/pipeline/OpenInterceptorTest.java
  test/src/main/java/me/devnatan/inventoryframework/internal/MockElementFactory.java
Labels: bug
